### ISSUE TITLE
antd  icon引入本地资源报错 

### ISSUE THREAD

**Issue by duxianwei520** [yedaodao/antd-local-icon#1]
如题  我这边是在我的引入less文件里面 加入了下面这行话
@icon-url: "./iconfont/iconfont"; // 把 iconfont 地址改到本地
这个资源从antd icon local的官网上下载的  
然后启动我的工程的时候会报如下的错误
antd.less:6Uncaught Error: Cannot find module "../../node_modules/antd/lib/style/core/iconfont/iconfont.eot"(…)

client?cb1f:47./~/antd/lib/style/core/iconfont/iconfont.eot
Module parse failed: D:\tgram\node_modules\antd\lib\style\core\iconfont\iconfont.eot Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)

**Comment by yedaodao** [comment]
不是使用这个库造成的问题，应该是你自己引入icon-url的路径有问题，可以试一下绝对路径
